# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dandanzhang/projects/IF97

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dandanzhang/projects/IF97

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dandanzhang/projects/IF97/CMakeFiles /Users/dandanzhang/projects/IF97/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dandanzhang/projects/IF97/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IF97

# Build rule for target.
IF97: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IF97
.PHONY : IF97

# fast build rule for target.
IF97/fast:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/build
.PHONY : IF97/fast

IF97.o: IF97.C.o

.PHONY : IF97.o

# target to build an object file
IF97.C.o:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/IF97.C.o
.PHONY : IF97.C.o

IF97.i: IF97.C.i

.PHONY : IF97.i

# target to preprocess a source file
IF97.C.i:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/IF97.C.i
.PHONY : IF97.C.i

IF97.s: IF97.C.s

.PHONY : IF97.s

# target to generate assembly for a file
IF97.C.s:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/IF97.C.s
.PHONY : IF97.C.s

cxx_main.o: cxx_main.C.o

.PHONY : cxx_main.o

# target to build an object file
cxx_main.C.o:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/cxx_main.C.o
.PHONY : cxx_main.C.o

cxx_main.i: cxx_main.C.i

.PHONY : cxx_main.i

# target to preprocess a source file
cxx_main.C.i:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/cxx_main.C.i
.PHONY : cxx_main.C.i

cxx_main.s: cxx_main.C.s

.PHONY : cxx_main.s

# target to generate assembly for a file
cxx_main.C.s:
	$(MAKE) -f CMakeFiles/IF97.dir/build.make CMakeFiles/IF97.dir/cxx_main.C.s
.PHONY : cxx_main.C.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... IF97"
	@echo "... IF97.o"
	@echo "... IF97.i"
	@echo "... IF97.s"
	@echo "... cxx_main.o"
	@echo "... cxx_main.i"
	@echo "... cxx_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

